### ISSUE TITLE
What is the correct format of the repo parameter

### ISSUE THREAD

**Issue by grejza** [interviewstreet/pr-stats#1]
Hi, 

struggling to get this working. What is the correct format of the repo parameter. Is it the bare git URL?

Thanks,
grejza

**Comment by rishiloyola** [comment]
@grejza : No it is not the git url, it is just the name of repo.
Example : **"pr-stats"** is the name of repo.

**Comment by grejza** [comment]
Thanks for coming back!!

I tried running this against your repo and didn't get any error (though not seeing any output):
./pr-stats interviewstreet pr-stats
Please enter your GitHub username: grejza
Please enter your GitHub password: 
Authenticating to GitHub using Username and Password as user grejza
You have 4997 GitHub API requests of 5000 remaining
Generating PR Statistics for repository interviewstreet/pr-stats

You have 4996 GitHub API requests of 5000 remaining
Generating statistics used 1 GitHub API requests

When I try to run it against my own repo I get bad credentials error. One big difference here is that my repo is not on github.com but <something>-github.<something>.com. Does your code assume the repo is in github.com? any way around it please?

**Comment by rishiloyola** [comment]
Yes, your code should be on github.com .
And actually my code stores all the data in a file and after that we are sending data to Kibana using logstash.
